#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true


# default lists actions
default:
  @just -f {{ source_file() }} --list

# get-swagger endpoint
invoke tenant="local" test_file="":
  #!/usr/bin/env bash
  set -eufo pipefail
  export HURL_VARS_FILE=hurl.{{ tenant }}.env

  mkdir -p ./out || true 

  if [[ ! -f $HURL_VARS_FILE ]]; then
    echo "$HURL_VARS_FILE not found"
  else
    hurl --very-verbose --test {{ test_file }} --variables-file $HURL_VARS_FILE 
  fi

# get-swagger endpoint
get-swagger tenant="local": 
  just invoke {{ tenant }} "get-swagger.hurl"

# get-ping endpoint
get-ping tenant="local": 
  just invoke {{ tenant }} "get-ping.hurl"

# get-count endpoint
get-count tenant="local": 
  just invoke {{ tenant }} "get-count.hurl"

# post-count endpoint
post-count tenant="local": 
  just invoke {{ tenant }} "post-count.hurl"

# put-count endpoint
put-count tenant="local": 
  just invoke {{ tenant }} "put-count.hurl"

# get-count endpoint
get-count-cors-fail tenant="local": 
  just invoke {{ tenant }} "put-count.hurl"


all tenant="local":
  just get-ping {{ tenant }}
  just get-count {{ tenant }}
  just post-count {{ tenant }}
  just put-count {{ tenant }}
  just get-count-cors-fail {{ tenant }}
  just get-swagger {{ tenant }}