#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f {{ source_file() }} --list

install:
  #!/usr/bin/env bash
  set -eufo pipefail

  cd ./backend
  just install
  cd ../frontend
  just install
  
backend-start:
  #!/usr/bin/env bash
  set -eufo pipefail

  cd ./backend
  just run start:dev

backend-run script="":
  #!/usr/bin/env bash
  set -eufo pipefail

  cd ./backend
  just {{ script }}

frontend-start:
  #!/usr/bin/env bash
  set -eufo pipefail

  cd ./frontend
  just run dev

frontend-run script="":
  #!/usr/bin/env bash
  set -eufo pipefail

  cd ./backend
  just {{ script }}

deploy:
  #!/usr/bin/env bash
  set -eufo pipefail

  cd ./backend
  just deploy
  cd ../frontend
  just deploy